"""Added time

Revision ID: 59f2f0395144
Revises: f6cb641a3581
Create Date: 2019-11-24 01:25:56.312581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f2f0395144'
down_revision = 'f6cb641a3581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_timestamp'), 'users', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_timestamp'), table_name='users')
    op.drop_column('users', 'timestamp')
    # ### end Alembic commands ###
